### PR TITLE
Add fifo queue support

### PR DESCRIPTION
**Pull request by mumia**
Adds support for creating/destroying/publishing/receiving messages to and from an AWS FIFO Queue

### CODE REVIEW

**Comment by tiagobrito** [comment]
@kmfk Can you review this implementation please?

**Comment by kmfk** [comment]
@mumia Was a little quick to merge that last PR, I just resolved the conflict I created by doing so

**Comment by francoispluchino** [comment]
@mumia Thanks for your work, however, there is a little bug with the push notification and FIFO queue. You can see the PR #124 for the fix.

**Comment by mumia** [comment]
@francoispluchino It seems I mislead you with my implementation.
SNS topic subscription is not currently support by AWS for FIFO Queues.
Check the "Compatibility" section on: http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html 

I will write a fix for my PR removing the push notification support on fifo queues.

**Comment by francoispluchino** [comment]
Indeed, the doc isn't updated regarding the regions available, but SNS is still not available with SQS FIFO. Thanks for your precision.

On the other hand, my PR fixes the error 400 `Invalid parameter: Topic Name`.

**Pull request merged**
