### PR TITLE
Added support for Iron MQ v3

### PR DESCRIPTION
**Pull request by brunoroux**
* use IronMQ API v3
* added rate_limit option (new queue option in v3)
* added queue info method

### CODE REVIEW

**Comment by tristanbes** [comment]
:+1: :)

**Comment by brunoroux** [comment]
Anyone had some time to take a look at this ?

**Comment by tristanbes** [comment]
ping @kmfk

**Comment by tristanbes** [comment]
@kmfk can you tag a new version please ?

**Comment by kmfk** [comment]
@tristanbes - v2.2.0 is up

**Pull request merged**
