### PR TITLE
Add support for AWS SQS new FIFO type queue

### PR DESCRIPTION
**Pull request by davidedonattini**

### CODE REVIEW

**Comment by tiagobrito** [comment]
👍

**Comment by mumia** [comment]
👍

**Comment by mumia** [comment]
This only seems to have the changes to send messages.
There are also changes to the creation of the queue itself:
 - Guarantee that the name of the queue has the suffix ".fifo"
 - Set the ```FifoQueue``` attribute on the creation request

Also there is an ability to generate the ```MessageDeduplicationId``` automatically (if not supplied) based on the content with the creation attribute ```ContentBasedDeduplication```

**Comment by kcassam** [comment]
+1

**Comment by kcassam** [comment]
👍

**Comment by kmfk** [comment]
Sorry for the delay - merged! Will get a new tag out.

**Comment by tiagobrito** [comment]
@kmfk This implementation seems to have a problem on the queue creation as @mumia mention.
Check is PR https://github.com/uecode/qpush-bundle/pull/120

**Comment by kmfk** [comment]
@tiagobrito Taking a look and will get things merged together

**Pull request merged**
